<template>
  <div>
    <div>工作台</div>
    <div>工作台</div>
    <div>工作台</div>
    <div>工作台</div>
    <div>工作台</div>
    <div>工作台</div>
    <div>工作台</div>
    <div>工作台</div>
    <div>工作台</div>
    <div>工作台</div>
    <div>工作台</div>
    <div>工作台</div>
    <div>工作台</div>
    <div>工作台</div>
    <div>工作台</div>
    <div>工作台</div>
    <div>工作台</div>
    <div>工作台</div>
    <div>工作台</div>
    <div>工作台</div>
    <div>工作台</div>
    <div>工作台</div>
    <div>工作台</div>
    <div>工作台</div>
    <div>工作台</div>
    <div>工作台</div>
    <div>工作台</div>
    <div>工作台</div>
    <div>工作台</div>
    <div>工作台</div>
    <div>工作台</div>
    <div>工作台</div>
    <div>工作台</div>
    <div>工作台</div>
    <div>工作台</div>
    <div>工作台</div>
    <div>工作台</div>
    <div>工作台</div>
    <div>工作台</div>
    <div>工作台</div>
    <div>工作台</div>
    <div>工作台</div>
    <div>工作台</div>
    <div>工作台</div>
    <div>工作台</div>
    <div>工作台</div>
    <div>工作台</div>
    <div>工作台</div>
    <div>工作台</div>
    <div>工作台</div>
    <div>工作台</div>
    <div>工作台</div>
    <div>工作台</div>
    <div>工作台</div>
    <div>工作台</div>
    <div>工作台</div>
    <div>工作台</div>
    <div>工作台</div>
    <div>工作台</div>
    <div>工作台</div>
    <div>工作台</div>
    <div>工作台</div>
    <div>工作台</div>
    <div>工作台</div>
    <div>工作台</div>
    <div>工作台</div>
    <div>工作台</div>
    <div>工作台</div>
    <div>工作台</div>
    <div>工作台</div>
    <div>工作台</div>
    <div>工作台</div>
    <div>工作台</div>
    <div>工作台</div>
    <div>工作台</div>
    <div>工作台</div>
    <div>工作台</div>
    <div>工作台</div>
    <div>工作台</div>
    <div>工作台</div>
    <div>工作台</div>
    <div>工作台</div>
    <div>工作台</div>
    <div>工作台</div>
    <div>工作台</div>
    <div>工作台</div>
    <div>工作台</div>
  </div>
</template>

<script setup lang="ts">
/********************************************************************************
 * @author Berlin
 ********************************************************************************/
</script>
