spring:
  application.name: abner-main
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test-store-wcs?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 1234qwer
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8081